### ISSUE TITLE
Convert .format to f-String

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#13]
Scattered throughout the repository there are `.format` functions. These should be replaced by the more modern `f"{...}"` format.

**Comment by mayankjainllrl** [comment]
hey, can I take this Issue?

**Comment by nilsgawlik** [comment]
Thanks for wanting to contribute! 
From my side, go ahead. Maybe Blinkenlights can still give their ok, to make sure they're not working on it (even though I don't think so)!

**Comment by mayankjainllrl** [comment]
Hey I am having some problems in sending pull request. Its my first time contributing to open source can you help?

**Comment by nilsgawlik** [comment]
No problem, if there are any specific questions ask ahead! Without additional information I don't really know where you're stuck, of course. I found this guide, which seems correct to me https://www.dataschool.io/how-to-contribute-on-github/. 
I see you forked the repository already, but I don't see any changes on it. I think after you've commited and pushed your changes to your forked repository you should be able to make a pull request from there.

**Comment by mayankjainllrl** [comment]
I have created a new branch in my forked repository and committed my changes there

**Comment by nilsgawlik** [comment]
I think you still need to push the changes to the branch in your forked repository, before you can make a pull request

**Comment by mayankjainllrl** [comment]
You were right I had not pushed the changes earlier, sorry this is my first contribution to open source. I had generated the pull request with the changes please review and provide feedback :-). @nilsgawlik

**Comment by mayankjainllrl** [comment]
Hey any changes needed in my code? You haven't merged my pull request.
@nilsgawlik

**Comment by nilsgawlik** [comment]
Hey, sorry I've just been really busy with other stuff. I've taken a quick look at the code and it looks good! I just wanted to test it out on my machine, to be sure everything works, so hopefully I'll get around to merging it tomorrow.

**Comment by nilsgawlik** [comment]
@mayankjainllrl I added you to the readme under a "with contributions from" section. I hope this is ok for you. If you want to be credited differently (or not credited for whatever reason), let me know!
