### ISSUE TITLE
Biome support (getBiomeAt function)

### ISSUE THREAD

**Issue by nilsgawlik** [nilsgawlik/gdmc_http_client_python#16]
**Feature branch:** `getbiome-implementation`

Add a function along the lines of `getBiomeAt(x, z)`.

x and z should be in world space, to be consistent with `getBlockAt`.

Alternatively it could also accept a tuple `pos = (x, z); getBiomeAt(pos)`, which would be more consistent with `getBlockAt` but also more confusing.

Additionally there could also be a "biome map", which would work exactly like the heightmaps.

**Comment by Flashing-Blinkenlights** [comment]
I think it would also make sense to include a getChunkBiomes or something to accommodate rougher biome searches, since the chunk data includes biome information.

**Comment by Flashing-Blinkenlights** [comment]
Getbiome functions implemented
