### ISSUE TITLE
Suggestion: Option in getBuildArea to get the area around a player

### ISSUE THREAD

**Issue by caranha** [nilsgawlik/gdmc_http_client_python#20]
**Feature branch: `improvement-allsorts`**

It would be nice to have an option (or maybe a separate function) to get the area around the player as the build area, if the build area is not set.

Example:
```python
def requestPlayerArea(dx=128, dz=128):
    runCommand(f"execute at @p run setbuildarea ~{-dx//2} 0 ~{-dz//2} ~{dx//2} 255 ~{dz//2}"
    return requestBuildArea()
```

**Comment by Flashing-Blinkenlights** [comment]
To be implemented in `interfaceUtils.py`

**Comment by Flashing-Blinkenlights** [comment]
Implemented and tested, some minor adjustments needed to be made
