### ISSUE TITLE
Replace functions

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#25]
**Feature branch: `improvement-allsorts`**

Currently, when replacing large areas of a particular block with another block, one must constantly call getBlock and setBlock.
It would be convenient to have a function that does this automatically.
An additional feature might be randomised block placement from a selection of blocks to provide more texture on large surfaces.

### Suggested implementation:

```py
def replace(x1, y1, z1, x2, y2, z2, searchBlock, replaceBlock):
    for x, y, z in loop3D(x1, y1, z1, x2, y2, z2):
        if interfaceUtils.getBlock(x, y, z) == searchBlock:
            if replaceBlock.type() == str:
                interfaceUtils.setBlock(x, y, z, replaceBlock)
            else:
                interfaceUtils.setBlock(x, y, z, random.choice(replaceBlock))
```

Pro:
- Ease of use when placing large surfaces
- Easy surface texturing and palette shifting

Con:
- [fill me]

**Comment by jithenshriyan** [comment]
Let me know if I could work on this. Saw you assigned yourself, but would you prefer me to take a shot at it?

**Comment by Flashing-Blinkenlights** [comment]
Hi @jithenshriyan! I'm sorry I didn't see your comment earlier. If you are still interested in contributing don't hesitate do contact me again!
