### ISSUE TITLE
Memoise getBlock

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#7]
**Feature branch: `getblock-memoisation`**

Adding a global/static block cache to be used by the Interface class would allow for faster getBlock calls without having to go via interface.

### Suggested implementation:
Calling setBlock or a heightmap function would update the cache, while getBlock would return the block from cache if available, otherwise updating the cache.
#### Example:
```py
>>> print(Interface.blockCache)
{(0, 0, 0): "minecraft:bedrock", (18, 171, -372): "minecraft:air"}
```

**Comment by nilsgawlik** [comment]
potential problems:
1) Cache isn't 100% guaranteed, because players can manually set blocks in Minecraft, or set blocks through a command. This could especially be problematic when trying to debug a program while not being aware that the cache exists.
2) The cache could get really big, really fast.

**Comment by Flashing-Blinkenlights** [comment]
>     1. Cache isn't 100% guaranteed, because players can manually set blocks in Minecraft, or set blocks through a command. This could especially be problematic when trying to debug a program while not being aware that the cache exists.

Make it an opt-in feature.
 
>     2. The cache could get really big, really fast.

Have the cache clear once it exceeds a certain size.

**Comment by nilsgawlik** [comment]
> Have the cache clear once it exceeds a certain size.
Actually it could be an OrderedDict, that way the oldest elements can be deleteted with oderedDict.popitem(False)

**Comment by Flashing-Blinkenlights** [comment]
An excellent idea!
I think I'll use an OrderedDict but have it call move_to_end with each update, so that the 'oldest' blocks are at the front.

**Comment by Flashing-Blinkenlights** [comment]
Getblock memoisation is implemented.
