### ISSUE TITLE
Integrate no-block-update functionality into setBlock

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#8]
Feature branch: `geometry`

It would be nice to give the user the option to not have their changes update the surrounding blocks, even if just for speed's sake.

**Comment by nilsgawlik** [comment]
The server side functionality was implemented in https://github.com/nilsgawlik/gdmc_http_interface/releases/tag/v0.4.0 

Now this feature still needs to be included in direct_interface.py. (and maybe higher level parts of the client as well?)
