### ISSUE TITLE
Determine a versioning scheme

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#9]
For compatibility and documentation purposes a version would be very convenient.

Legend:
- `increment`: A number representing the total amount of versions on the main branch
- `development_phase`: A sequence representing the current stage in development (e.g. 0 for in development, 1 for released, 2 for official GDMC)
- `minecraft_version`: A sequence representing the last compatible version of Minecraft (e.g. 16 for version 1.16.)
- `date`: A sequence representing the date the version was last modified (e.g. a month, year or date)

Format suggestions:
- `{increment}.{development_phase}.{date}`: e.g. `6.2.210312`
- `{year}.{month}.{day}`: e.g. `21.03.12`
- `{development_phase}.{minecraft_version}.{month}`: e.g. `0.16.03`

**Comment by nilsgawlik** [comment]
So is this about this repo only, or does it also concern the interface itself? 
For the http interface I've been using {major version}.{minor version}.{fix}, but I'm not super attached to it.
If we are talking about this repo only it would make sense to tie it more to the version of the http interface than to the Minecraft version

**Comment by nilsgawlik** [comment]
There is also the question of if there are ever going to be multiple 'forks' in parallel, for example if we push fixes to the master, but develop features on dev at the same time.

**Comment by Flashing-Blinkenlights** [comment]
Hmm, good point.
I think I would keep the interface and implementation versions seperate, since there will likely be more implementation versions then interface versions.
How about something like {interface version}.{minecraft version}.{fix} with fix being {branch}{version} e.g. dev_12?

**Comment by Flashing-Blinkenlights** [comment]
It has been decided to use the following system:

`{GMDC year}.{increment}_{branch}`
E.g. `v5.0_dev`
